### ISSUE TITLE
Malford public key

### ISSUE THREAD

**Issue by ArpitDadh** [dmop/node-adyen-encrypt#1]
When I try to integrate it in my React app..

I used "Origin key" provided by Adyen as the "adyenKey" 

//   var adyenKey     =  'pub.v2.8015565304900201.aHR0cHM6Ly9kZXYubGxlc3VvcmFjLmNvbQ.kSRpd4gWCUF0K1E2WaXAODtk3_HXGy9q9wyFi8TAu6s'; 
    //  var options = {}; // See adyen-encrypt.js for details
    //  var cardData = {
    //      number : '5577 0000 5577 0004',       // 'xxxx xxxx xxxx xxxx'
    //      cvc : '737',                 //'xxx'
    //      holderName : 'customer',   // 'John Doe'
    //      expiryMonth : '10', //'MM'
    //      expiryYear : '2020',   // 'YYYY'
    //      generationtime : new Date().toISOString() // new Date().toISOString()
    //  };
    //  var cseInstance = adyenEncrypt.createEncryption(adyenKey, options);
    //  cseInstance.validate(cardData);
    //  console.log(cseInstance);
    //  var dataEncrypted = cseInstance.encrypt(cardData); 
    //  console.log(dataEncrypted);

I used these Dummy data. 

It gives me "cseInstance.encrypt(cardData)" this as a "Malford public key".

Can you please help me in this. I am stuck
Thanks in advance.
@dmop

**Comment by dmop** [comment]
Update the package please

**Comment by Mattesackboy** [comment]
@ArpitDadh Did you solve this? I have the same problem with my originKey "pub.v2.1115434210450369.aHR0cHM6Ly93d3cuYXctbGFiLmNvbQ.bvvCQj8xdpi0fvEKIAB1-EEgqV_mMcb1MGzkDKNm9Q8"
It seems that the lib expects a key with "|" inside.
@dmop I know that is deprecated but I need to use it for reverse engineer a payment site, do you know any solution?
